version: '2'
services:
  hadoop-slave1:
    image: hadoop/slave
    hostname: hadoop-slave1
  hadoop-slave2:
    image: hadoop/slave
    hostname: hadoop-slave2
  hadoop-master:
    image: hadoop/master
    hostname: hadoop-master
    ports:
      - 8088:8088
      - 50070:50070
