version: '2'
services:
  hadoop-slave1:
    image: hadoop/yarn
    hostname: hadoop-slave1
  hadoop-slave2:
    image: hadoop/yarn
    hostname: hadoop-slave2
  hadoop-master:
    image: hadoop/yarn
    hostname: hadoop-master
    environment:
      HADOOP_MASTER: 1
    ports:
      - 8088:8088
      - 50070:50070
